import Head from 'next/head';
import React from 'react';
import { Inter } from '@next/font/google';
import Header from '../components/header';
import Footer from '../components/footer';
import About from '../components/about';

import Competence from '../components/competence';
import Project from '../components/projets';



const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <> 
    <Head>
      <title>Pla Fortea Diego - My portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className='bg-white  h-screen w-screen absolute  '>
      <Header/>
      <div className='text-black  '>
        <div className='flex '>
          <div className='flex-col w-full'>
            <h1 className='font-mono md:text-6xl text-lg p-20 mt-20 ml-20 pb-2 '>Développeur Fullstack</h1>
            <h3 className='font-sans md:text-4xl text-lg mx-7 p-20 ml-20 pb-10 '>Diego Pla Fortea</h3>    
            <a href='/CV_Diego_Pla_Fortea.pdf'target="_blank" className='border-t border-white   bg-gray-800 text-white px-10 py-2 rounded-lg  hover:bg-white hover:text-gray-800 hover:border-gray-800 font-mono mx-32 md:text-xl text-xs '>Téléchager le CV</a>
          </div>
          <img src='/photo.jpg' alt='' className='ml-auto rounded-full mr-20 w-3/12 pt-20 hidden md:block '></img>
        </div>
        <div className='bg-white'> 
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#1F2937" fill-opacity="1" d="M0,160L60,176C120,192,240,224,360,208C480,192,600,128,720,106.7C840,85,960,107,1080,128C1200,149,1320,171,1380,181.3L1440,192L1440,320L1380,320C1320,320,1200,320,1080,320C960,320,840,320,720,320C600,320,480,320,360,320C240,320,120,320,60,320L0,320Z"></path></svg>
        </div>
        <About/>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320" className='bg-white mt'><path fill="#1F2937" fill-opacity="1" d="M0,224L60,229.3C120,235,240,245,360,213.3C480,181,600,107,720,90.7C840,75,960,117,1080,154.7C1200,192,1320,224,1380,240L1440,256L1440,0L1380,0C1320,0,1200,0,1080,0C960,0,840,0,720,0C600,0,480,0,360,0C240,0,120,0,60,0L0,0Z"></path></svg>
        <Competence/>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320" className='bg-white mt'><path fill="#1F2937" fill-opacity="1" d="M0,128L60,133.3C120,139,240,149,360,165.3C480,181,600,203,720,192C840,181,960,139,1080,112C1200,85,1320,75,1380,69.3L1440,64L1440,320L1380,320C1320,320,1200,320,1080,320C960,320,840,320,720,320C600,320,480,320,360,320C240,320,120,320,60,320L0,320Z"></path></svg>
        
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320" className='bg-white mt'><path fill="#1F2937" fill-opacity="1" d="M0,224L34.3,218.7C68.6,213,137,203,206,186.7C274.3,171,343,149,411,149.3C480,149,549,171,617,197.3C685.7,224,754,256,823,250.7C891.4,245,960,203,1029,176C1097.1,149,1166,139,1234,149.3C1302.9,160,1371,192,1406,208L1440,224L1440,0L1405.7,0C1371.4,0,1303,0,1234,0C1165.7,0,1097,0,1029,0C960,0,891,0,823,0C754.3,0,686,0,617,0C548.6,0,480,0,411,0C342.9,0,274,0,206,0C137.1,0,69,0,34,0L0,0Z"></path></svg>
        <Project/>      
        </div>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320" className='bg-white mt'><path fill="#1F2937" fill-opacity="1" d="M0,128L60,133.3C120,139,240,149,360,165.3C480,181,600,203,720,192C840,181,960,139,1080,112C1200,85,1320,75,1380,69.3L1440,64L1440,320L1380,320C1320,320,1200,320,1080,320C960,320,840,320,720,320C600,320,480,320,360,320C240,320,120,320,60,320L0,320Z"></path></svg>
        <Footer/>
      </div> 
    </>
  );
}
